### ISSUE TITLE
BigDecimal.new is deprecated

### ISSUE THREAD

**Issue by TeamNautilus** [jethroo/lare_round#2]
We have installed the gem, but when we run our tests many warnings happens.

The warnings are of type:
.../gems/lare_round-0.0.2/lib/lare_round.rb:85: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
.../gems/lare_round-0.0.2/lib/lare_round.rb:89: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Can you fix this warning?

Thank you
Team Nautilus

**Comment by jethroo** [comment]
Thanks for reporting this @TeamNautilus 

I released version 0.0.3 just as of now which should fix the issue (#3). Note that with the new release I dropped the support for eol ruby versions. 

Please update your Gemfile accordingly: 

```
gem 'lare_round', '~> 0.0.3'
```

Also feel free to report back when facing other issues 😃

**Comment by jethroo** [comment]
closing due to beeing resolved :shipit:
