### ISSUE TITLE
Requires BigDecimal?

### ISSUE THREAD

**Issue by toobulkeh** [jethroo/lare_round#5]
Hey there, thanks for this quick algorithm! Super helpful to not have to build it on our project!

The errors are a bit annoying when using `float` instead of `BigDecimal`, specially for something as small as percentages or cents, but it's workable!

Just wanted to let you know this was still awesome in 2020 :)

**Comment by jethroo** [comment]
@toobulkeh thanks alot ;)

either you can fork the gem and silence the warning as needed for your purpose or I can add another optional flag to make them silencable upon call 

```ruby
LareRound.round(values: values, precision: precision, with_warnings: false)
```

but you know since everyone is busy this might take a while 😅 

belated: happy new 2021
